### ISSUE TITLE
Spotlight

### ISSUE THREAD

**Issue by JJonesey4002** [ryans1230/HeliCam#1]
The spotlight part of the script does not work for me, The person i had convert it and build it said he had issues building it and had to "There was an issue building it because there were conflicts between the system.draw and citizenfx references when it came to Color, So I made an alias for system.draw that's it". I am unsure what he or i can do here.

**Comment by ryans1230** [comment]
Not sure why you are getting any errors, as everything has been tested. Do you have a more descript error?

**Comment by JJonesey4002** [comment]
> Not sure why you are getting any errors, as everything has been tested. Do you have a more descript error?

That's the best information he could give me, in all honesty i think it would be easier to maybe upload both open formats and ready to go resource for fivem bud as some of us love this script but really don't know where to start... The only thing im having an error with is the spotlight so maybe send me the .dll files for client/server script?
