### ISSUE TITLE
Resource

### ISSUE THREAD

**Issue by Dehzmised** [ryans1230/HeliCam#6]
Why cant you just upload it as a FiveM resource as you made it to be one instead of making it difficult etc. It would be very much appreciated by multiple people if you were able to do that. Thanks!

**Comment by ryans1230** [comment]
1. It's not that hard to build the project.
2. I don't intend on providing any support for it. If I feel compelled to update/add features, I may do so in the future.
3. Why does every FiveM server owner need everything spoon fed to them?

**Comment by Dehzmised** [comment]
1. Not everyone is knowledgeable in this field.
2. Uploading the resource isn't "support". It's common sense for when you upload a FiveM Resource to put it in fivem resource format.
3. Putting it in the correct format isn't spoon feeding. It's really common sense and just an overall ease because we just want to use a cool script and instead of making a fivem resource FiveM Ready you decide to make it so we have to build it. Which many of us don't know how to do so leaving us empty or having to pay someone to do it instead of you just simply making it a drag and drop resource.
