### ISSUE TITLE
Package

### ISSUE THREAD

**Issue by Micah-B-SS** [ryans1230/HeliCam#8]
So I'm not a scripting type of person and not very tech savy so to say, but I'm really interested in this script and the only problem is the fact that it needs to be built I'm being told. If there was a way for it to be built already and I could get that I would love that. If you can't do that I understand just I am really interested and not wanting to use the other heli script.

**Comment by Capnau** [comment]
Dude are unblind https://github.com/ryans1230/HeliCam/releases/tag/1.0.0
